version: "3.8"

services:
  origin:
    build: ./origin-server
    container_name: origin-server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    env_file:
      - ./origin-server/.env

  api1:
    build: ./cdn-node
    container_name: api1
    environment:
      - NODE_ID=api1
      - PORT=3000
      - ORIGIN_URL=http://origin:4000
    env_file:
      - ./cdn-node/.env
    depends_on:
      - origin

  api2:
    build: ./cdn-node
    container_name: api2
    environment:
      - NODE_ID=api2
      - PORT=3000
      - ORIGIN_URL=http://origin:4000
    env_file:
      - ./cdn-node/.env
    depends_on:
      - origin

  api3:
    build: ./cdn-node
    container_name: api3
    environment:
      - NODE_ID=api3
      - PORT=3000
      - ORIGIN_URL=http://origin:4000
    env_file:
      - ./cdn-node/.env
    depends_on:
      - origin

  nginx:
    image: nginx:alpine
    container_name: cdn-load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api1
      - api2
      - api3
